def string(a):
    print(a[2])
    print(a[-2])
    print(a[:5])
    print(a[:len(a)-2])
    print(a[::2])
    print(a[1::2])
    print(a[::-1])
    print(a[-1::-2])
    print(len(a))
string('candies')